#!/usr/bin/env python3
"""Deterministic JAC word count for the canonical JAC manuscript.

Counts the main text (Introduction through end of Discussion) and the structured
synopsis of paper/jac/JAC_manuscript.tex, excluding the title page, tables, figure
legends/alt text, section headings, in-text citation markers, and back matter —
the JAC Original Article counting scope. Writes paper/jac/JAC_wordcount_report.md.

    python3 scripts/jac_wordcount.py        # from the repo root; or `make jac-wordcount`
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEX = ROOT / "paper" / "jac" / "JAC_manuscript.tex"
OUT = ROOT / "paper" / "jac" / "JAC_wordcount_report.md"

SECTIONS = ["Introduction", "Materials and methods", "Results", "Discussion"]


def _count(fragment: str) -> int:
    b = fragment
    b = re.sub(r"\\begin\{table\}.*?\\end\{table\}", "", b, flags=re.S)
    b = re.sub(r"\\begin\{figure\}.*?\\end\{figure\}", "", b, flags=re.S)
    b = re.sub(r"Alt text:.*", "", b)
    b = re.sub(r"\\(sub)?section\*\{[^}]*\}", "", b)
    b = re.sub(r"\\cite\{[^}]*\}", "", b)
    b = re.sub(r"\\[a-zA-Z]+\*?", "", b).replace("{", "").replace("}", "")
    b = re.sub(r"[~\\$^_&%]", " ", b)
    return len(re.findall(r"[A-Za-z0-9][A-Za-z0-9'./%-]*", b))


def counts(tex: str) -> dict:
    body = re.search(r"\\section\*\{Introduction\}(.*?)\\section\*\{Acknowledgements\}", tex, re.S).group(1)
    per = {}
    for i, sec in enumerate(SECTIONS):
        nxt = SECTIONS[i + 1] if i + 1 < len(SECTIONS) else "Acknowledgements"
        seg = re.search(r"\\section\*\{" + re.escape(sec) + r"\}(.*?)\\section\*\{" + re.escape(nxt) + r"\}", tex, re.S).group(1)
        per[sec] = _count(seg)
    syn = re.search(r"\\textbf\{\\large Synopsis\}(.*?)\\linenumbers", tex, re.S)
    return {"per": per, "main": _count(body), "synopsis": _count(syn.group(1)) if syn else None}


def report(c: dict) -> str:
    rows = "\n".join(f"| {k} | {v} |" for k, v in c["per"].items())
    return f"""# JAC_wordcount_report.md

**Rule (JAC IFA):** Original Article main text limit **3500 words**, counted
**Introduction through end of Discussion**; structured synopsis **250 words** maximum.
Excludes title page, synopsis, tables, figure legends/alt text, section headings,
in-text citation markers, and back matter. **Generated by `scripts/jac_wordcount.py`**
(`make jac-wordcount`) over `paper/jac/JAC_manuscript.tex`; re-run to reproduce.

## Main text (Introduction → end of Discussion)

| Section | Words |
|---|---:|
{rows}
| **Total** | **{c['main']}** |

**Limit 3500 — {'PASS' if c['main'] <= 3500 else 'OVER'}.**

## Synopsis

Structured (Background / Objectives / Methods / Results / Conclusions):
**{c['synopsis']} words** — limit 250 — **{'PASS' if (c['synopsis'] or 0) <= 250 else 'OVER'}**.
"""


def main() -> None:
    c = counts(TEX.read_text())
    OUT.write_text(report(c))
    print(f"main text {c['main']}/3500; synopsis {c['synopsis']}/250 -> wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
